version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile   # ✅ use "Dockerfile" (not ".dockerfile")
    container_name: backend_service
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=production
      - PORT=8002
    healthcheck:                # ✅ added backend healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8002/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

    frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  container_name: frontend
  ports:
    - "3000:80"   # map host 3000 to container port 80
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost/"]
    interval: 10s
    timeout: 5s
    retries: 5
